name: Auto Sync

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00.  https://crontab.guru/
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 'write' access to repository contents
    steps:
      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo
      - name: Checkout upstram
        uses: actions/checkout@v2
        with:
          repository: slidevjs/slidev
          fetch-depth: 0

      - name: Extract docs
        run: git filter-repo --subdirectory-filter docs --force

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: refs/heads/upstream
